version: '3'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
     - 9092:9092
     - 9094:9094
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kowl:
    image: quay.io/cloudhut/kowl:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: "kafka:9092"  # имя контейнера Kafka

  postgres:
    image: postgres:latest
    container_name: cloud_postgres
    ports:
        - "5500:5432"
    environment:
        - POSTGRES_USER=myuser
        - POSTGRES_PASSWORD=mysecretpassword
        - POSTGRES_DB=postgres

    volumes:
        - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
   
volumes:
  postgres_data:
  redis_data: